CREATE TABLE `test.covid19_global` (
	`index` BIGINT, 
	`DATE` DATETIME, 
	`Afghanistan` BIGINT, 
	`Albania` BIGINT, 
	`Algeria` BIGINT, 
	`Andorra` BIGINT, 
	`Angola` BIGINT, 
	`Antigua and Barbuda` BIGINT, 
	`Argentina` BIGINT, 
	`Armenia` BIGINT, 
	`Australia` BIGINT, 
	`Austria` BIGINT, 
	`Azerbaijan` BIGINT, 
	`Bahamas` BIGINT, 
	`Bahrain` BIGINT, 
	`Bangladesh` BIGINT, 
	`Barbados` BIGINT, 
	`Belarus` BIGINT, 
	`Belgium` BIGINT, 
	`Belize` BIGINT, 
	`Benin` BIGINT, 
	`Bhutan` BIGINT, 
	`Bolivia` BIGINT, 
	`Bosnia and Herzegovina` BIGINT, 
	`Botswana` BIGINT, 
	`Brazil` BIGINT, 
	`Brunei` BIGINT, 
	`Bulgaria` BIGINT, 
	`Burkina Faso` BIGINT, 
	`Burma` BIGINT, 
	`Burundi` BIGINT, 
	`Cabo Verde` BIGINT, 
	`Cambodia` BIGINT, 
	`Cameroon` BIGINT, 
	`Canada` BIGINT, 
	`Central African Republic` BIGINT, 
	`Chad` BIGINT, 
	`Chile` BIGINT, 
	`China` BIGINT, 
	`Colombia` BIGINT, 
	`Comoros` BIGINT, 
	`Congo Brazzaville` BIGINT, 
	`Congo Kinshasa` BIGINT, 
	`Costa Rica` BIGINT, 
	`Cote d'Ivoire` BIGINT, 
	`Croatia` BIGINT, 
	`Cuba` BIGINT, 
	`Cyprus` BIGINT, 
	`Czechia` BIGINT, 
	`Denmark` BIGINT, 
	`Diamond Princess` BIGINT, 
	`Djibouti` BIGINT, 
	`Dominica` BIGINT, 
	`Dominican Republic` BIGINT, 
	`Ecuador` BIGINT, 
	`Egypt` BIGINT, 
	`El Salvador` BIGINT, 
	`Equatorial Guinea` BIGINT, 
	`Eritrea` BIGINT, 
	`Estonia` BIGINT, 
	`Eswatini` BIGINT, 
	`Ethiopia` BIGINT, 
	`Fiji` BIGINT, 
	`Finland` BIGINT, 
	`France` BIGINT, 
	`Gabon` BIGINT, 
	`Gambia` BIGINT, 
	`Georgia` BIGINT, 
	`Germany` BIGINT, 
	`Ghana` BIGINT, 
	`Greece` BIGINT, 
	`Grenada` BIGINT, 
	`Guatemala` BIGINT, 
	`Guinea` BIGINT, 
	`Guinea-Bissau` BIGINT, 
	`Guyana` BIGINT, 
	`Haiti` BIGINT, 
	`Holy See` BIGINT, 
	`Honduras` BIGINT, 
	`Hungary` BIGINT, 
	`Iceland` BIGINT, 
	`India` BIGINT, 
	`Indonesia` BIGINT, 
	`Iran` BIGINT, 
	`Iraq` BIGINT, 
	`Ireland` BIGINT, 
	`Israel` BIGINT, 
	`Italy` BIGINT, 
	`Jamaica` BIGINT, 
	`Japan` BIGINT, 
	`Jordan` BIGINT, 
	`Kazakhstan` BIGINT, 
	`Kenya` BIGINT, 
	`Korea, South` BIGINT, 
	`Kosovo` BIGINT, 
	`Kuwait` BIGINT, 
	`Kyrgyzstan` BIGINT, 
	`Laos` BIGINT, 
	`Latvia` BIGINT, 
	`Lebanon` BIGINT, 
	`Lesotho` BIGINT, 
	`Liberia` BIGINT, 
	`Libya` BIGINT, 
	`Liechtenstein` BIGINT, 
	`Lithuania` BIGINT, 
	`Luxembourg` BIGINT, 
	`MS Zaandam` BIGINT, 
	`Madagascar` BIGINT, 
	`Malawi` BIGINT, 
	`Malaysia` BIGINT, 
	`Maldives` BIGINT, 
	`Mali` BIGINT, 
	`Malta` BIGINT, 
	`Marshall Islands` BIGINT, 
	`Mauritania` BIGINT, 
	`Mauritius` BIGINT, 
	`Mexico` BIGINT, 
	`Moldova` BIGINT, 
	`Monaco` BIGINT, 
	`Mongolia` BIGINT, 
	`Montenegro` BIGINT, 
	`Morocco` BIGINT, 
	`Mozambique` BIGINT, 
	`Namibia` BIGINT, 
	`Nepal` BIGINT, 
	`Netherlands` BIGINT, 
	`New Zealand` BIGINT, 
	`Nicaragua` BIGINT, 
	`Niger` BIGINT, 
	`Nigeria` BIGINT, 
	`North Macedonia` BIGINT, 
	`Norway` BIGINT, 
	`Oman` BIGINT, 
	`Pakistan` BIGINT, 
	`Panama` BIGINT, 
	`Papua New Guinea` BIGINT, 
	`Paraguay` BIGINT, 
	`Peru` BIGINT, 
	`Philippines` BIGINT, 
	`Poland` BIGINT, 
	`Portugal` BIGINT, 
	`Qatar` BIGINT, 
	`Romania` BIGINT, 
	`Russia` BIGINT, 
	`Rwanda` BIGINT, 
	`Saint Kitts and Nevis` BIGINT, 
	`Saint Lucia` BIGINT, 
	`Saint Vincent and the Grenadines` BIGINT, 
	`Samoa` BIGINT, 
	`San Marino` BIGINT, 
	`Sao Tome and Principe` BIGINT, 
	`Saudi Arabia` BIGINT, 
	`Senegal` BIGINT, 
	`Serbia` BIGINT, 
	`Seychelles` BIGINT, 
	`Sierra Leone` BIGINT, 
	`Singapore` BIGINT, 
	`Slovakia` BIGINT, 
	`Slovenia` BIGINT, 
	`Solomon Islands` BIGINT, 
	`Somalia` BIGINT, 
	`South Africa` BIGINT, 
	`South Sudan` BIGINT, 
	`Spain` BIGINT, 
	`Sri Lanka` BIGINT, 
	`Sudan` BIGINT, 
	`Suriname` BIGINT, 
	`Sweden` BIGINT, 
	`Switzerland` BIGINT, 
	`Syria` BIGINT, 
	`Taiwan*` BIGINT, 
	`Tajikistan` BIGINT, 
	`Tanzania` BIGINT, 
	`Thailand` BIGINT, 
	`Timor-Leste` BIGINT, 
	`Togo` BIGINT, 
	`Trinidad and Tobago` BIGINT, 
	`Tunisia` BIGINT, 
	`Turkey` BIGINT, 
	`US` BIGINT, 
	`Uganda` BIGINT, 
	`Ukraine` BIGINT, 
	`United Arab Emirates` BIGINT, 
	`United Kingdom` BIGINT, 
	`Uruguay` BIGINT, 
	`Uzbekistan` BIGINT, 
	`Vanuatu` BIGINT, 
	`Venezuela` BIGINT, 
	`Vietnam` BIGINT, 
	`West Bank and Gaza` BIGINT, 
	`Yemen` BIGINT, 
	`Zambia` BIGINT, 
	`Zimbabwe` BIGINT
)
