CREATE TABLE `test.unconfirmed_transactions` (
	`index` BIGINT, 
	sequence BIGINT, 
	witness TEXT, 
	script_x TEXT, 
	`prev_out.spent` BOOL, 
	`prev_out.spending_outpoints` TEXT, 
	`prev_out.tx_index` BIGINT, 
	`prev_out.type` BIGINT, 
	`prev_out.addr` TEXT, 
	`prev_out.value` BIGINT, 
	`prev_out.n` BIGINT, 
	`prev_out.script` TEXT, 
	lock_time_x BIGINT, 
	ver_x BIGINT, 
	size_x BIGINT, 
	weight_x BIGINT, 
	time_x BIGINT, 
	hash TEXT, 
	spent BOOL, 
	tx_index BIGINT, 
	type BIGINT, 
	addr TEXT, 
	value BIGINT, 
	n BIGINT, 
	script_y TEXT, 
	spending_outpoints TEXT, 
	lock_time_y BIGINT, 
	ver_y BIGINT, 
	size_y BIGINT, 
	weight_y BIGINT, 
	time_y BIGINT, 
	CHECK (`prev_out.spent` IN (0, 1)), 
	CHECK (spent IN (0, 1))
)